name: "Build and Test"

on: [push, workflow_dispatch, pull_request]

jobs:

  instrumented-tests:
    name: "Instrumented Tests"
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Instrumented Tests"
        uses: reactivecircus/android-emulator-runner@v2.20.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: "Archive Instrumented Tests Results"
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: "instrumented-tests-results"
          path: ./**/build/reports/androidTests/connected/**

  unit-tests:
    name: "Unit Tests"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Unit Tests"
        run: ./gradlew test
      - name: "Android Unit Tests Report"
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: "unit-tests-results"
          path: ./**/build/reports/**

  lint-checks:
    name: "Lint Checks"
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Android Lint"
        run: ./gradlew lint
      - name: "Archive Lint Test Results"
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: "lint-results"
          path: ./**/build/reports/**

  kotlin-lint-checks:
    name: "Kotlin Lint Checks"
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Kotlin Lint"
        run: ./gradlew ktlintCheck
      - name: "Archive Lint Test Results"
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: "kotlin-lint-results"
          path: ./**/build/reports/**

  automerge-dependabot:
    name: "Save PR Number for Dependabot Automerge"
    needs: [ instrumented-tests, unit-tests, lint-checks, kotlin-lint-checks ]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout PR branch"
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: "Save Pull Request Number"
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
